// Code generated by protoc-gen-go. DO NOT EDIT.
// source: selection.proto

package selectionpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateSelectionRequest struct {
	AppId                string    `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	UserId               string    `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ServerId             string    `protobuf:"bytes,3,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Options              []*Option `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateSelectionRequest) Reset()         { *m = CreateSelectionRequest{} }
func (m *CreateSelectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSelectionRequest) ProtoMessage()    {}
func (*CreateSelectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_selection_d6a05eb1d2d57e6b, []int{0}
}
func (m *CreateSelectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSelectionRequest.Unmarshal(m, b)
}
func (m *CreateSelectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSelectionRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSelectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSelectionRequest.Merge(dst, src)
}
func (m *CreateSelectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSelectionRequest.Size(m)
}
func (m *CreateSelectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSelectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSelectionRequest proto.InternalMessageInfo

func (m *CreateSelectionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateSelectionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateSelectionRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *CreateSelectionRequest) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type Option struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string            `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_selection_d6a05eb1d2d57e6b, []int{1}
}
func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (dst *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(dst, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Option) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Option) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SelectionOption struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string            `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SelectionOption) Reset()         { *m = SelectionOption{} }
func (m *SelectionOption) String() string { return proto.CompactTextString(m) }
func (*SelectionOption) ProtoMessage()    {}
func (*SelectionOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_selection_d6a05eb1d2d57e6b, []int{2}
}
func (m *SelectionOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectionOption.Unmarshal(m, b)
}
func (m *SelectionOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectionOption.Marshal(b, m, deterministic)
}
func (dst *SelectionOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectionOption.Merge(dst, src)
}
func (m *SelectionOption) XXX_Size() int {
	return xxx_messageInfo_SelectionOption.Size(m)
}
func (m *SelectionOption) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectionOption.DiscardUnknown(m)
}

var xxx_messageInfo_SelectionOption proto.InternalMessageInfo

func (m *SelectionOption) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SelectionOption) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SelectionOption) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreateSelectionReply struct {
	SelectionOptions     []*SelectionOption `protobuf:"bytes,1,rep,name=selectionOptions,proto3" json:"selectionOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateSelectionReply) Reset()         { *m = CreateSelectionReply{} }
func (m *CreateSelectionReply) String() string { return proto.CompactTextString(m) }
func (*CreateSelectionReply) ProtoMessage()    {}
func (*CreateSelectionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_selection_d6a05eb1d2d57e6b, []int{3}
}
func (m *CreateSelectionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSelectionReply.Unmarshal(m, b)
}
func (m *CreateSelectionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSelectionReply.Marshal(b, m, deterministic)
}
func (dst *CreateSelectionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSelectionReply.Merge(dst, src)
}
func (m *CreateSelectionReply) XXX_Size() int {
	return xxx_messageInfo_CreateSelectionReply.Size(m)
}
func (m *CreateSelectionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSelectionReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSelectionReply proto.InternalMessageInfo

func (m *CreateSelectionReply) GetSelectionOptions() []*SelectionOption {
	if m != nil {
		return m.SelectionOptions
	}
	return nil
}

type ParseSelectionRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ServerId             string   `protobuf:"bytes,3,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseSelectionRequest) Reset()         { *m = ParseSelectionRequest{} }
func (m *ParseSelectionRequest) String() string { return proto.CompactTextString(m) }
func (*ParseSelectionRequest) ProtoMessage()    {}
func (*ParseSelectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_selection_d6a05eb1d2d57e6b, []int{4}
}
func (m *ParseSelectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseSelectionRequest.Unmarshal(m, b)
}
func (m *ParseSelectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseSelectionRequest.Marshal(b, m, deterministic)
}
func (dst *ParseSelectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseSelectionRequest.Merge(dst, src)
}
func (m *ParseSelectionRequest) XXX_Size() int {
	return xxx_messageInfo_ParseSelectionRequest.Size(m)
}
func (m *ParseSelectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseSelectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseSelectionRequest proto.InternalMessageInfo

func (m *ParseSelectionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ParseSelectionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ParseSelectionRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ParseSelectionRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type RankedOption struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rank                 int32    `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankedOption) Reset()         { *m = RankedOption{} }
func (m *RankedOption) String() string { return proto.CompactTextString(m) }
func (*RankedOption) ProtoMessage()    {}
func (*RankedOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_selection_d6a05eb1d2d57e6b, []int{5}
}
func (m *RankedOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankedOption.Unmarshal(m, b)
}
func (m *RankedOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankedOption.Marshal(b, m, deterministic)
}
func (dst *RankedOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankedOption.Merge(dst, src)
}
func (m *RankedOption) XXX_Size() int {
	return xxx_messageInfo_RankedOption.Size(m)
}
func (m *RankedOption) XXX_DiscardUnknown() {
	xxx_messageInfo_RankedOption.DiscardUnknown(m)
}

var xxx_messageInfo_RankedOption proto.InternalMessageInfo

func (m *RankedOption) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RankedOption) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type ParseSelectionReply struct {
	RankedOptions        []*RankedOption `protobuf:"bytes,1,rep,name=rankedOptions,proto3" json:"rankedOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ParseSelectionReply) Reset()         { *m = ParseSelectionReply{} }
func (m *ParseSelectionReply) String() string { return proto.CompactTextString(m) }
func (*ParseSelectionReply) ProtoMessage()    {}
func (*ParseSelectionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_selection_d6a05eb1d2d57e6b, []int{6}
}
func (m *ParseSelectionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseSelectionReply.Unmarshal(m, b)
}
func (m *ParseSelectionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseSelectionReply.Marshal(b, m, deterministic)
}
func (dst *ParseSelectionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseSelectionReply.Merge(dst, src)
}
func (m *ParseSelectionReply) XXX_Size() int {
	return xxx_messageInfo_ParseSelectionReply.Size(m)
}
func (m *ParseSelectionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseSelectionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ParseSelectionReply proto.InternalMessageInfo

func (m *ParseSelectionReply) GetRankedOptions() []*RankedOption {
	if m != nil {
		return m.RankedOptions
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSelectionRequest)(nil), "selectionpb.CreateSelectionRequest")
	proto.RegisterType((*Option)(nil), "selectionpb.Option")
	proto.RegisterMapType((map[string]string)(nil), "selectionpb.Option.MetadataEntry")
	proto.RegisterType((*SelectionOption)(nil), "selectionpb.SelectionOption")
	proto.RegisterMapType((map[string]string)(nil), "selectionpb.SelectionOption.MetadataEntry")
	proto.RegisterType((*CreateSelectionReply)(nil), "selectionpb.CreateSelectionReply")
	proto.RegisterType((*ParseSelectionRequest)(nil), "selectionpb.ParseSelectionRequest")
	proto.RegisterType((*RankedOption)(nil), "selectionpb.RankedOption")
	proto.RegisterType((*ParseSelectionReply)(nil), "selectionpb.ParseSelectionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SelectionClient is the client API for Selection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SelectionClient interface {
	CreateSelection(ctx context.Context, in *CreateSelectionRequest, opts ...grpc.CallOption) (*CreateSelectionReply, error)
	ParseSelection(ctx context.Context, in *ParseSelectionRequest, opts ...grpc.CallOption) (*ParseSelectionReply, error)
}

type selectionClient struct {
	cc *grpc.ClientConn
}

func NewSelectionClient(cc *grpc.ClientConn) SelectionClient {
	return &selectionClient{cc}
}

func (c *selectionClient) CreateSelection(ctx context.Context, in *CreateSelectionRequest, opts ...grpc.CallOption) (*CreateSelectionReply, error) {
	out := new(CreateSelectionReply)
	err := c.cc.Invoke(ctx, "/selectionpb.Selection/CreateSelection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selectionClient) ParseSelection(ctx context.Context, in *ParseSelectionRequest, opts ...grpc.CallOption) (*ParseSelectionReply, error) {
	out := new(ParseSelectionReply)
	err := c.cc.Invoke(ctx, "/selectionpb.Selection/ParseSelection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelectionServer is the server API for Selection service.
type SelectionServer interface {
	CreateSelection(context.Context, *CreateSelectionRequest) (*CreateSelectionReply, error)
	ParseSelection(context.Context, *ParseSelectionRequest) (*ParseSelectionReply, error)
}

func RegisterSelectionServer(s *grpc.Server, srv SelectionServer) {
	s.RegisterService(&_Selection_serviceDesc, srv)
}

func _Selection_CreateSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelectionServer).CreateSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selectionpb.Selection/CreateSelection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelectionServer).CreateSelection(ctx, req.(*CreateSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Selection_ParseSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelectionServer).ParseSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selectionpb.Selection/ParseSelection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelectionServer).ParseSelection(ctx, req.(*ParseSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Selection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "selectionpb.Selection",
	HandlerType: (*SelectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSelection",
			Handler:    _Selection_CreateSelection_Handler,
		},
		{
			MethodName: "ParseSelection",
			Handler:    _Selection_ParseSelection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "selection.proto",
}

func init() { proto.RegisterFile("selection.proto", fileDescriptor_selection_d6a05eb1d2d57e6b) }

var fileDescriptor_selection_d6a05eb1d2d57e6b = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcb, 0x8a, 0xdb, 0x30,
	0x14, 0xad, 0xec, 0x3c, 0x6f, 0x9a, 0x07, 0x4a, 0x1a, 0x5c, 0xd3, 0x45, 0xa2, 0x6e, 0x42, 0xa1,
	0x5e, 0xa4, 0x9b, 0xd2, 0x52, 0xba, 0x28, 0x2d, 0xcd, 0xa2, 0xb4, 0xa8, 0x50, 0x0a, 0xb3, 0x19,
	0x25, 0xd6, 0x22, 0xc4, 0x63, 0x7b, 0x24, 0x25, 0x60, 0xe6, 0x2b, 0xe6, 0x47, 0xe6, 0x1b, 0x86,
	0xf9, 0xb2, 0xc1, 0x8a, 0x6d, 0xac, 0x38, 0x93, 0x59, 0x65, 0xa7, 0xfb, 0x3a, 0xe7, 0xe8, 0xf8,
	0x5a, 0xd0, 0x97, 0x3c, 0xe0, 0x2b, 0xb5, 0x8e, 0x42, 0x2f, 0x16, 0x91, 0x8a, 0x70, 0xa7, 0x48,
	0xc4, 0x4b, 0x72, 0x8b, 0x60, 0xfc, 0x4d, 0x70, 0xa6, 0xf8, 0xdf, 0x3c, 0x4b, 0xf9, 0xf5, 0x96,
	0x4b, 0x85, 0x47, 0x50, 0x67, 0x71, 0xbc, 0xf0, 0x1d, 0x34, 0x41, 0xb3, 0x36, 0xdd, 0x07, 0x78,
	0x0c, 0x8d, 0xad, 0xe4, 0x62, 0xe1, 0x3b, 0x96, 0x4e, 0x67, 0x11, 0x76, 0xa1, 0x25, 0xb9, 0xd8,
	0xe9, 0x8a, 0xad, 0x2b, 0x45, 0x8c, 0xdf, 0x43, 0x33, 0x8a, 0x53, 0x68, 0xe9, 0xd4, 0x26, 0xf6,
	0xac, 0x33, 0x1f, 0x7a, 0x25, 0x0d, 0xde, 0x6f, 0x5d, 0xa3, 0x79, 0x0f, 0xb9, 0x43, 0xd0, 0xd8,
	0xe7, 0x70, 0x0f, 0xac, 0x75, 0x2e, 0xc0, 0x5a, 0xfb, 0xd8, 0x81, 0xe6, 0x2a, 0x0a, 0x15, 0x0f,
	0x55, 0x46, 0x9f, 0x87, 0xf8, 0x0b, 0xb4, 0xae, 0xb8, 0x62, 0x3e, 0x53, 0xcc, 0xb1, 0x35, 0xc9,
	0xf4, 0x08, 0x89, 0xf7, 0x2b, 0xeb, 0xf9, 0x1e, 0x2a, 0x91, 0xd0, 0x62, 0xc4, 0xfd, 0x0c, 0x5d,
	0xa3, 0x84, 0x07, 0x60, 0x6f, 0x78, 0x92, 0x51, 0xa7, 0xc7, 0xd4, 0x8f, 0x1d, 0x0b, 0xb6, 0x3c,
	0x63, 0xde, 0x07, 0x9f, 0xac, 0x8f, 0x88, 0xdc, 0x23, 0xe8, 0x17, 0xf6, 0x55, 0x94, 0xd7, 0x9f,
	0x51, 0xfe, 0xa3, 0xa2, 0xfc, 0x9d, 0xa1, 0xfc, 0x00, 0xf9, 0x3c, 0x57, 0xb8, 0x84, 0x51, 0x65,
	0x0d, 0xe2, 0x20, 0xc1, 0x3f, 0x61, 0x20, 0x4d, 0x7e, 0xe9, 0x20, 0x2d, 0xf2, 0xcd, 0x29, 0x91,
	0xb4, 0x32, 0x45, 0x6e, 0xe0, 0xd5, 0x1f, 0x26, 0xe4, 0x39, 0xf7, 0xac, 0xe4, 0x71, 0xcd, 0xf0,
	0x98, 0xcc, 0xe1, 0x25, 0x65, 0xe1, 0x86, 0xfb, 0x4f, 0xec, 0x15, 0x86, 0x9a, 0x60, 0xe1, 0x46,
	0x73, 0xd5, 0xa9, 0x3e, 0x93, 0x7f, 0x30, 0x3c, 0x14, 0x9c, 0x3a, 0xf2, 0x15, 0xba, 0xa2, 0x04,
	0x95, 0xdb, 0xf1, 0xda, 0xb0, 0xa3, 0x4c, 0x46, 0xcd, 0xfe, 0xf9, 0x03, 0x82, 0x76, 0x81, 0x89,
	0x2f, 0xa0, 0x7f, 0x60, 0x3c, 0x7e, 0x6b, 0x40, 0x1d, 0xff, 0x3b, 0xdd, 0xe9, 0xe9, 0xa6, 0x38,
	0x48, 0xc8, 0x0b, 0xfc, 0x1f, 0x7a, 0xe6, 0x15, 0x30, 0x31, 0xc6, 0x8e, 0x7e, 0x10, 0x77, 0x72,
	0xb2, 0x47, 0x23, 0x2f, 0x1b, 0xfa, 0x2d, 0xf9, 0xf0, 0x18, 0x00, 0x00, 0xff, 0xff, 0x65, 0x82,
	0x52, 0x42, 0x5e, 0x04, 0x00, 0x00,
}
